{
  "uid" : "1dedca6c96625dc0",
  "name" : "test_broken",
  "fullName" : "testdemo.python-allure使用#test_broken",
  "historyId" : "2dd18f3719921a30641489bd07b18c5e",
  "time" : {
    "start" : 1635060717643,
    "stop" : 1635060717644,
    "duration" : 1
  },
  "status" : "broken",
  "statusMessage" : "Exception: oops",
  "statusTrace" : "def test_broken():\n>       raise Exception(\"oops\")\nE       Exception: oops\n\ntestdemo\\python-allure使用.py:13: Exception",
  "flaky" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "testdemo"
  }, {
    "name" : "suite",
    "value" : "python-allure使用"
  }, {
    "name" : "host",
    "value" : "010A05050057"
  }, {
    "name" : "thread",
    "value" : "2256-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testdemo.python-allure使用"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "1dedca6c96625dc0.json",
  "parameterValues" : [ ]
}